name: Docker Image CI

on:
  push:
    branches:
      - "release"
  pull_request:
    branches:
      - "release"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CTR_USER: ${{ secrets.CTR_USER }}
  CTR_TOKEN: ${{ secrets.CTR_TOKEN }}


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out Repo
        uses: actions/checkout@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.CTR_USER }}
          password: ${{ env.CTR_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
